name: openfcu
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  dio: ^5.1.1
  dio_cookie_manager: ^3.0.0
  cookie_jar: ^4.0.1
  html: ^0.15.2
  http: ^0.13.5
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.4.4